const options = [
    {
        "table-view": true,
        inputType: "input",
        type: "text",
        label: "First Name",
        key: "firstName",
        name: "firstName",
        placeholder: "Enter your first name",
        prefix: "",
        suffix: "",
        multiple: false,
        value: "",
        protected: false,
        unique: false,
        persistent: true,
        required: false,
        minLength: "",
        maxLength: "",
        custom: "",
        customPrivate: false,
        autofocus: false,
        hidden: false,
        spellcheck: true
    },
    {
        "table-view": true,
        inputType: "input",
        type: "text",
        label: "Last Name",
        key: "lastName",
        name: "lastName",
        placeholder: "Enter your last name",
        prefix: "",
        suffix: "",
        multiple: false,
        value: "",
        protected: false,
        unique: false,
        persistent: true,
        required: false,
        minLength: "",
        maxLength: "",
        custom: "",
        customPrivate: false,
        autofocus: false,
        hidden: false,
        spellcheck: true
    },
    {
        inputType: "input",
        type: "email",
        autofocus: false,
        input: true,
        tableView: true,
        label: "Email",
        key: "email",
        placeholder: "",
        prefix: "",
        suffix: "",
        defaultValue: "",
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        inputFormat: "plain"
    },
    {
        inputType: "textarea",
        type: "textarea",
        autofocus: false,
        input: true,
        tableView: true,
        label: "Text Area",
        key: "textArea",
        placeholder: "",
        prefix: "",
        suffix: "",
        rows: 6,
        multiple: false,
        defaultValue: "",
        protected: false,
        persistent: true,
        hidden: false,
        wysiwyg: false,
        clearOnHide: true,
        spellcheck: true,
        required: false,
        minLength: "",
        maxLength: "",
        pattern: "",
        custom: "",
    },
    {
        inputType: "button",
        type: "submit",
        theme: "primary",
        disableOnInvalid: true,
        action: "submit",
        block: false,
        rightIcon: "",
        leftIcon: "",
        size: "md",
        key: "submit",
        tableView: false,
        label: "Submit",
        input: true,
        autofocus: false,
    }
]


export default options;